[versions]
kotlin = "1.6.10"
coroutines = "1.6.0"
detekt = "1.19.0"
junit = "5.8.2"
dokka = "1.6.10"
mockk = "1.12.3"
koin2 = "2.2.3"
koin3 = "3.1.5"
ktor = "2.0.1"
jackson = "2.13.1"
versions = "0.42.0"
gradleTestLogger = "3.2.0"
kotlinBcv = "0.8.0"
hoplite = "2.1.4"
jimfs = "1.2"
slf4j = "1.7.36"
logback = "1.2.11"

[libraries]
# Dependencies

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-host = { module = "io.ktor:ktor-server-host-common", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-contentNegotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-serialization-jackson = { module = "io.ktor:ktor-serialization-jackson", version.ref = "ktor" }

jackson-time = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }

hoplite-json = { module = "com.sksamuel.hoplite:hoplite-json", version.ref = "hoplite" }
hoplite-yaml = { module = "com.sksamuel.hoplite:hoplite-yaml", version.ref = "hoplite" }
hoplite-toml = { module = "com.sksamuel.hoplite:hoplite-toml", version.ref = "hoplite" }

jimfs = { module = "com.google.jimfs:jimfs", version.ref = "jimfs" }

slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

# Test dependencies

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

junit-jupiterApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiterEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }

# Detekt plugins

detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

[plugins]

kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
gradleTestLogger = { id = "com.adarshr.test-logger", version.ref = "gradleTestLogger" }
kotlinBcv = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "kotlinBcv" }
