name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-wrapper:
    name: "Validate Gradle wrapper"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1

  check:
    name: "Run tests & checks"
    runs-on: ubuntu-latest
    needs: [validate-wrapper]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - run: ./gradlew check --no-daemon

  build-dokka:
    name: "Generate Dokka files"
    runs-on: ubuntu-latest
    needs: [validate-wrapper]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Generate Dokka documentation
        run: ./gradlew :website:rewriteDokkaLinks --no-daemon
      - uses: actions/upload-artifact@v3
        with:
          name: dokka-output
          path: website/build/dokkaHtml

  build-docs:
    name: "Build Docusaurus"
    needs: [validate-wrapper]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - uses: actions/setup-node@v3
      - run: npm i -g pnpm
      - run: pnpm install
        working-directory: docs
      - name: Build Docusaurus site
        run: ./gradlew :docs:docusaurusBuild --no-daemon
      - uses: actions/upload-artifact@v3
        with:
          name: docusaurus-output
          path: docs/build
   
  build-deploy-website:
    name: Build and deploy website
    needs: [validate-wrapper, build-docs, build-dokka]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      # TODO maybe unnecessary
      - uses: actions/setup-node@v3
      - uses: actions/download-artifact@v3
        with:
          name: dokka-output
          path: website/build/dokkaHtml
      - uses: actions/download-artifact@v3
        with:
          name: docusaurus-output
          path: docs/build
      # -x parameters ensure that we use output from previous builds and that we do not re-run the builds here
      - run: ./gradlew :website:assembleFiles --no-daemon -x :website:rewriteDokkaLinks -x :docs:docusaurusBuild
      - uses: BetaHuhn/deploy-to-vercel-action@v1.9.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          PRODUCTION: "false"
          WORKING_DIRECTORY: "website/build/output"
