name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-wrapper:
    name: "Validate Gradle wrapper"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1

  check:
    name: "Run tests & checks"
    runs-on: ubuntu-latest
    needs: [validate-wrapper]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - run: ./gradlew check

  build-dokka:
    name: "Generate Dokka files"
    runs-on: ubuntu-latest
    needs: [validate-wrapper]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Generate Dokka documentation
        run: ./gradlew :website:rewriteDokkaLinks

      - uses: actions/upload-artifact@v3
        with:
          name: dokka-output
          path: website/build/dokkaHtml
          retention-days: 3

  build-docs:
    name: "Build Docusaurus"
    needs: [validate-wrapper]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - run: npm i -g pnpm

      - run: pnpm install
        working-directory: docs

      - run: pnpm run build
        working-directory: docs

      - uses: actions/upload-artifact@v3
        with:
          name: docusaurus-output
          path: docs/build
          retention-days: 3

  build-deploy-website:
    name: Assemble and deploy website
    needs: [validate-wrapper, build-docs, build-dokka, check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # TODO maybe unnecessary
      - uses: actions/setup-node@v3

      - name: Download Dokka build
        uses: actions/download-artifact@v3
        with:
          name: dokka-output
          path: website/build/dokkaHtml

      - name: Download Docusaurus build
        uses: actions/download-artifact@v3
        with:
          name: docusaurus-output
          path: docs/build

      # -x parameters ensure that we use output from previous builds and that we do not re-run the builds here
      - name: Assemble website files
        run: ./gradlew :website:assembleFiles -x :website:rewriteDokkaLinks -x :docs:docusaurusBuild

      - name: Deploy to Vercel
        uses: BetaHuhn/deploy-to-vercel-action@v1.9.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          WORKING_DIRECTORY: "website/build/output"
